# docker-compose.yml (Thêm service ShortenUrl)
version: '3.8'

services:
  # Tạm thời, nếu bạn dùng LocalDB, bạn có thể không cần service DB container 
  # Nếu bạn cần DB container (để CI/CD hoạt động trên GitHub Actions):
  # mssql-db: 
  #   image: mcr.microsoft.com/mssql/server:2019-latest 

  shortenurl-api:
    container_name: shortenurl_api_service
    build:
      context: . # Solution root
      dockerfile: ShortenUrl/Dockerfile # Chỉ đến Dockerfile đã tạo ở trên
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - "8081:80" # Dùng để kiểm tra trực tiếp

